### ISSUE TITLE
ocarina-docker fails on Archlinux

### ISSUE THREAD

**Issue by dordow** [OpenAADL/ocarina-docker#2]
I have tried ocarina-docker on Archlinux 5.6.3-arch1-1 with docker version 19.03.8-ce, build afacb8b7f0, but without success.

Trying to build **centos-7.x-gnat-community-2018** failed with:

```shell
--2020-04-17 20:11:14--  http://mirrors.cdn.adacore.com/art/5b0d7bffa3f5d709751e3e04
Resolving mirrors.cdn.adacore.com (mirrors.cdn.adacore.com)... failed: Name or service not known.
wget: unable to resolve host address ‘mirrors.cdn.adacore.com’
The command '/bin/sh -c cd $HOME &&     wget http://mirrors.cdn.adacore.com/art/5b0d7bffa3f5d709751e3e04 -O gnat-community-2018 &&     git clone https://github.com/AdaCore/gnat_community_install_script &&     sh ./gnat_community_install_script/install_package.sh ./gnat-community-2018 $HOME/gnat-community-2018-install' returned a non-zero code: 4
```

Trying to build **centos-7.x-gnat-gpl-2017** failed with same error message, basically

```shell
get: unable to resolve host address ‘mirrors.cdn.adacore.com’
The command '/bin/sh -c cd $HOME &&     wget -nv http://mirrors.cdn.adacore.com/art/591c6d80c7a447af2deed1d7 &&     mv  591c6d80c7a447af2deed1d7 gnat-gpl-2017-x86_64-linux-bin.tar.gz &&     tar zxf gnat-gpl-2017-x86_64-linux-bin.tar.gz' returned a non-zero code: 4
```

Trying to build **debian-10.0** was succesfull, but running fails:

```shell
docker run -t -i ocarina/build bash
```

did not work at all, and

```shell
docker run -t ocarina/build 
```

started but failed with

```shell
configure: error: I could not find gprbuild. .
```

Before that there where warnings concernign the locale:

```shell
warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LANG = "C"
    are supported and installed on your system.
```

A final test with **debian-testing** showed the same behaviour as debian-10.0. Getting the dependencies of all the required Ada packages right on Arch is very demanding.

**Comment by yoogx** [comment]
For GNAT GPL/CE, AdaCore changed the URL of their repository. 
For Debian, I added the installation for gprbuild, it works for debian-10.0

**Comment by dordow** [comment]
Installation now works with debian-10.0 as suggested, but I cannot get it to run. I must admit that I am a first time Docker user, I just went through a very basic tutorial, so the question may be stupid.
I run
```shell
docker run -t ocarina/build 
```
which now went to completion, and tells me to add the following paths:
/home/ocarina/local/lib to LD_LIBRARY_PATH
/home/ocarina/local/bin to PATH

However, both paths do not exist in the host environment.
I started the container with
```shell
docker run -t -i ocarina/build bash
```
which opened a shell. The paths mentioned above are also not in the container environment.
Is there some fancy stuff with dockers I should know to get it running? 
Thanks in advance

**Comment by yoogx** [comment]
Check this patch, I had to extend the Dockerfile, it was no meant to run Ocarina.
You have two options; either you use ocarina from Archlinux through the docker container. But you need to have build chain installed in ArchLinux (which should be OK for C targets)

or you jump in the container; and do everything from there.

I only documented the first case.
